version: "3.8"

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/supervisor.conf:/etc/supervisor/conf.d/server.conf
        networks:
            - app-network
        ports:
            - 8092:${APP_PORT}
            - "5173:5173"
        restart: on-failure
        links:
            - redis
            - mariadb
        depends_on:
            - redis
            - mariadb
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mariadb:
        image: mariadb:10.9.3
        volumes:
            - app-database-volume:/var/lib/mysql
            - ./docker/database:/docker-entrypoint-initdb.d
            - ./docker/database/conf:/etc/mysql/conf.d
        networks:
            - app-network
        environment:
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_PWD=${DB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}
        ports:
            - "3307:${DB_PORT}"
        restart: always
        healthcheck:
            test: [ "CMD", "mariadb-admin", "--protocol", "tcp" ,"ping" ]
            timeout: 3m
            interval: 10s
            retries: 10

    redis:
        image: redis:7.0
        ports:
            - 16381:${REDIS_PORT}
        restart: always
        networks:
            - app-network

    node:
        image: node:18
        working_dir: /app
        volumes:
            - ./:/app
        command: bash -c "npm install && npm run dev"

networks:
    app-network:
        driver: bridge
volumes:
    app-database-volume:
        driver: local
