version: "3.9"

services:
    php:
        container_name: php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/supervisor.conf:/etc/supervisor/conf.d/server.conf
        networks:
            - app-network
        ports:
            - ${APP_PORT}:8092
            - ${DEV_SERVER_PORT}:5173
        restart: on-failure
        depends_on:
            - redis
            - mariadb
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mariadb:
        container_name: mariadb
        image: mariadb:10.9.3
        volumes:
            - app-database-volume:/var/lib/mysql
            - ./docker/database:/docker-entrypoint-initdb.d
            - ./docker/database/conf:/etc/mysql/conf.d
        networks:
            - app-network
        environment:
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_PWD=${DB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}
        ports:
            - ${DB_PORT}:3306
        restart: always
        healthcheck:
            test: [ "CMD", "mariadb-admin", "--protocol", "tcp" ,"ping" ]
            timeout: 3m
            interval: 10s
            retries: 10

    redis:
        container_name: redis
        image: redis:7.0
        ports:
            - ${REDIS_PORT}:6379
        restart: always
        volumes:
            - 'app-redis-volume:/data'
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    node:
        container_name: node
        image: node:18
        working_dir: /app
        volumes:
            - ./:/app
        command: bash -c "npm install && npm run dev"

networks:
    app-network:
        driver: bridge
volumes:
    app-database-volume:
        driver: local
    app-redis-volume:
        driver: local
